FROM ubuntu:20.04
LABEL mainteiner = "Erick de Jesus Pérez Macias"
LABEL description = "Pagina dentro de un contenedor que utiliza PHP y SQLite en Ubuntu "
LABEL version = "0.1"
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt -y install php7.4
RUN apt -y install apache2
RUN apt -y install php libapache2-mod-php
RUN apt -y install php-cli
RUN apt -y install php-cgi
RUN apt -y install sqlite3
RUN apt-get install php7.4-sqlite3 -y
EXPOSE 8080/tcp

